### PR TITLE
fix MQTT subscriber host issue

### PR DESCRIPTION
**Pull request by jinfahua**
The fix patch for [this issue](https://github.com/edgexfoundry/go-mod-messaging/issues/50)

### CODE REVIEW

**Comment by lenny-intel** [comment]
This PR will work if only Publishing or only Subscribing and solves the issue #51, but....

The MessageBus was designed to allow both Publishing and Subscribing to/from the same or different hosts. It should be able to connect to the PublishHost and or the SubscribeHost, so the MQTT implementation needs to handle the case when both are specified, but are different hosts, i.e. make two connections or when they are the same host and make only one connection.

Question is do we want to handle this second part in a different issue and PR? @AnthonyMBonafide , @tsconn23 thoughts?

**Comment by lenny-intel** [comment]
@jinfahua , your changes are causing unit test failures. Please resolve.

**Comment by jinfahua** [comment]
> @jinfahua , your changes are causing unit test failures. Please resolve.

@lenny-intel Fixed, and rebased commits. Could you please review it again?

**Comment by lenny-intel** [comment]
@jinfahua , now you have `gofmt` issues. We run `gofmt` from the `make test` target. Please run `make tests` and resolve the formatting issue.
```
[2020-04-14T03:54:20.982Z] gofmt -l .

[2020-04-14T03:54:20.982Z] internal/pkg/mqtt/client_options.go

[2020-04-14T03:54:20.982Z] internal/pkg/mqtt/client_test.go

[2020-04-14T03:54:20.982Z] [ "`gofmt -l .`" = "" ]

[2020-04-14T03:54:20.982Z] make: *** [Makefile:9: test] Error 1
```

**Comment by jinfahua** [comment]
I fixed, and it prints as following... Not sure if it's OK now?

```shell
$ make test
CGO_ENABLED=1 GO111MODULE=on go test ./... -coverprofile=coverage.out ./...
?       github.com/edgexfoundry/go-mod-messaging/internal/pkg   [no test files]
ok      github.com/edgexfoundry/go-mod-messaging/internal/pkg/mqtt      0.016s  coverage: 95.4% of statements
ok      github.com/edgexfoundry/go-mod-messaging/internal/pkg/zeromq    20.428s coverage: 84.1% of statements
ok      github.com/edgexfoundry/go-mod-messaging/messaging      0.014s  coverage: 100.0% of statements
ok      github.com/edgexfoundry/go-mod-messaging/messaging/mqtt 0.014s  coverage: 100.0% of statements
ok      github.com/edgexfoundry/go-mod-messaging/pkg/types      0.015s  coverage: 90.9% of statements
CGO_ENABLED=1 GO111MODULE=on go vet ./...
gofmt -l .
[ "`gofmt -l .`" = "" ]

```

**Comment by lenny-intel** [comment]
> Not sure if it's OK now?

Yep, that looks good.

**Pull request merged**
