### PR TITLE
Add minimum supported Go version 1.12 to go.mod.

### LINKED ISSUE #34: Add minimum supported Go version to go.mod
Locally, I've upgraded to Go 1.13 to test it out. The project hasn't officially rev'ed to that version yet. One of the things I notice is that when I do a `make test` on a module, an entry indicating go 1.13 as the minimum supported version is put into the go.mod. According to the following article, we should have started seeing this behavior with Go 1.12, but I don't recall that being the case

https://golang.org/doc/go1.12#modules

I wouldn't want this to be checked in as go 1.13 until the project moves to that version. I've tested compilation of the edgex-go services locally with the version directive set to go 1.12 and everything works as far as I can tell. Again, this directive is only indicating a minimum supported version.

I think we should do this fairly soon as we could easily get contributions from people who've upgraded to Go 1.13 and who might miss this small edit.

### PR DESCRIPTION
**Pull request by akramtexas**
Fix #34 

Locally, I upgraded to Go `1.12`, and tested it out via `Makefile`.

### CODE REVIEW

**Comment by lenny-intel** [comment]
Note that these changes have upstream CI impacts and need to be coordinated with DevOps @ernestojeda, @jamesrgregg, @lranjbar , @tsconn23  . Services that use this module will be required to upgrade to 1.13 and the CI build images will need to change to a 1.13 version.

**Comment by lenny-intel** [comment]
> Note that these changes have upstream CI impacts and need to be coordinated with DevOps @ernestojeda, @jamesrgregg, @lranjbar , @tsconn23 . Services that use this module will be required to upgrade to 1.13 and the CI build images will need to change to a 1.13 version.

Sorry, I thought I saw this as the bump to 1.13, now it saw 1.12...

**Comment by akramtexas** [comment]
Recheck

**Comment by akramtexas** [comment]
Recheck

**Comment by akramtexas** [comment]
@lranjbar I'm seeing that error (which we had run into a few days ago) now showing up again in [the log of the failed build check](https://jenkins.edgexfoundry.org/blue/rest/organizations/jenkins/pipelines/edgexfoundry/pipelines/go-mod-messaging/branches/PR-38/runs/3/log/?start=0):
```
ERROR: Project Settings File id (settingsFile) is required for the docker login script.
Finished: FAILURE
```

**Comment by lranjbar** [comment]
The old verify pipeline has been removed now to stop the double builds. Need to rebase off the master branch and push.

**Comment by akramtexas** [comment]
> The old verify pipeline has been removed now to stop the double builds. Need to rebase off the master branch and push.

@lranjbar I will do so, ASAP, thanks 👍

**Comment by akramtexas** [comment]
Rebased.

**Comment by lranjbar** [comment]
LGTM. New build is passing, just seems like Github is not wanting to clear out the old build check.

**Comment by michaelestrin** [comment]
I can't merge until go-mod-messaging-verify-pipeline is addressed @lranjbar.

image

**Pull request merged**
